spring:
  application:
    name: booking-app
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: booking_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true